### ISSUE TITLE
Create a good map of the 3rd floor MHT (in real)

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/uol-openday-robot#1]
should at least cover 
- [x] the path from Lift to Research Lab
- [x] the path through the OpenDay coffee area (area where Greg's and Kevin's offices are located), passing by the printer
- [x] the path to MC3108

additionally:
- [x] the route via the LISC area can be added, but is lower priority

Take care:
- do not enter the offices themselves (only research lab)
- close the loop

**Comment by markrosoft** [comment]
The Robot was patrolled slowly in reverse from 
- her charging base in MC3106
- Past the stair way near the PHD students.
- Back down the main corridor 
- thoroughly explored the OpenDay coffee area. 
- towards the lift and peering into it.
- completing the loop around the outside of the coffee area,
- moving towards and past Comp Lab C caused it to crash (Linda ... localhome/Home/Crash-3-7-0230.txt)
