### ISSUE TITLE
Document COB people recognition and detection

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/uol-openday-robot#10]
- [x] how to start
- [x] how to compile and integrate into your catkin WS
- [ ] what information is provided (topics)
- [ ] how to interact with the COB system (trigger training, reset training, ...)

**Comment by cdondrup** [comment]
Compilation and integration is explained here: https://github.com/LCAS/uol-openday-robot/wiki/Set-up

**Comment by cdondrup** [comment]
See: https://github.com/LCAS/uol-openday-robot/wiki/running-attention_head for start-up.

**Comment by pet1330** [comment]
"how to interact with the COB system (trigger training, reset training, ...) " -  this point is not needed as COB doesn't need training, it is pre-trained.

**Comment by cdondrup** [comment]
The people detection is pre-trained that's right. But I think the training part refers to the people recognition which we are not using at the moment.
