### ISSUE TITLE
Implement PersonAttention behaviour

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/uol-openday-robot#13]
This is based on cob_people_detection and has to be implemented as an [actionlib::ActionServer](http://www.ros.org/doc/api/actionlib/html/classactionlib_1_1ActionServer.html). This shall then be called from the SMACH controller (see #12). 
In this simple first behaviour, the robot's head moves from person to person, resting on each for a couple of (random) seconds. When no person is found for some time the behaviour returns as not succeeded. The behaviour can be properly cancelled.

**Comment by cdondrup** [comment]
Doing transformation from camera to head coordinate system.
- Create (or implement in your existing code) a tf::TransformListener like in this tutorial: http://www.ros.org/wiki/tf/Tutorials/Writing%20a%20tf%20listener%20%28C%2B%2B%29
- Perform transformation from /head_xtion_depth_optical_frame to /base_link and then transform to head by adding the hight of the head to Z
  - Alternatively, write transformation for head as child of /base_link

To view possible transformations:
- run `rqt` on Linda and add ROS tf plugin
- run `rosrun tf tf_echo /head_xtion_depth_optical_frame /base_link` on Linda to see the desired transformation.
