### ISSUE TITLE
ToDoList - Thursday

### ISSUE THREAD

**Issue by markrosoft** [LCAS/uol-openday-robot#19]
Fix imports on patroller.py

Create a Launch File
- Rviz Waypoint setup

Documentation
- How to create a map
- How to use Rviz waypoint
- How to create/add/edit speach scripts
- Description of programs
- comment good.

**Comment by cdondrup** [comment]
Thursday is long gone.
Will split up remaining tasks into new issues.

**Comment by pet1330** [comment]
:+1:  Good Plan. This issue was meant to of been closed ages ago.
