### ISSUE TITLE
Choose person detection method and try it out

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/uol-openday-robot#2]
There are several options. Look at them, choose, and try out.
- [x] COB toolbox: 
  - https://github.com/strands-project/vision#face-detection-using-cob_perception-
  - [slides of as talk at ROSCon](http://roscon.ros.org/2013/wp-content/uploads/2013/06/people_perception.pdf)
  - [video of that talk itself](http://vimeo.com/66969071)
- [x] Standard [OpenCV face detection](http://opencv.willowgarage.com/wiki/FaceDetection)
- [x] Legs detection using 2D laser:
  - [ROS node from TUM](http://tum-ros-pkg.svn.sourceforge.net/viewvc/tum-ros-pkg/perception/people_detector_node/) 
  - [Paper about the method](http://webpages.lincoln.ac.uk/omozos/publications/arras2007icra.pdf)
  - [Example video](http://webpages.lincoln.ac.uk/omozos/multimedia/AdaBoostOffice.avi)

**Comment by marc-hanheide** [comment]
I think we'll stick to cob for now and then later integrate Oscar's laser detection once that is ready to go.

**Comment by cdondrup** [comment]
Leg detection has been implemented. See: https://github.com/cdondrup/hesitation_study/tree/master/leg_detector_tf
Will be catkinzed as soon as possible to incorporate it into the strands-project repository.
