### ISSUE TITLE
Design a first task for the open day

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/uol-openday-robot#8]

**Comment by marc-hanheide** [comment]
I think this has more or less been decided now. My summary:
- the robot moves to pre-defined positions
- these positions can be easily taught either by moving the robot with the joystick to those positions or by clicking in RViz (similar functionality as waypoint_patroller)
- at each of these waypoints a behaviour shall be triggered (using actionlib)

Now, @pet1330 and @markrosoft simply have to implement it :-)

**Comment by pet1330** [comment]
This hasn't been implemented yet, should it have been closed?

**Comment by marc-hanheide** [comment]
I think we spent enough time discussing and designing the task. Now it's time to implement it, but we'll discuss in a few minutes. For now, check the other issues that are much more specific, and associated to a milestone that I think would be the next step. Happy to disucss: https://github.com/LCAS/uol-openday-robot/issues?milestone=2&state=open

**Comment by marc-hanheide** [comment]
sorry, wrong link, I meant this one: https://github.com/LCAS/uol-openday-robot/issues/milestones
